export const data = [
  {
    custid: 1,
    month: 'May',
    monthNumber: 5,
    name: 'Smith',
    numTransactions: 3,
    points: 159,
    totalPointsByCustomer: 762,
  },
  {
    custid: 1,
    month: 'June',
    monthNumber: 6,
    name: 'Smith',
    numTransactions: 2,
    points: 25,
    totalPointsByCustomer: 762,
  },
  {
    custid: 1,
    month: 'July',
    monthNumber: 7,
    name: 'Smith',
    numTransactions: 4,
    points: 578,
    totalPointsByCustomer: 762,
  },
  {
    custid: 2,
    month: 'May',
    monthNumber: 5,
    name: 'Bob',
    numTransactions: 2,
    points: 125,
    totalPointsByCustomer: 698,
  },
  {
    custid: 2,
    month: 'June',
    monthNumber: 6,
    name: 'Bob',
    numTransactions: 2,
    points: 25,
    totalPointsByCustomer: 698,
  },
  {
    custid: 2,
    month: 'July',
    monthNumber: 7,
    name: 'Bob',
    numTransactions: 2,
    points: 548,
    totalPointsByCustomer: 698,
  },
  {
    custid: 3,
    month: 'July',
    monthNumber: 7,
    name: 'John',
    numTransactions: 2,
    points: 90,
    totalPointsByCustomer: 90,
  },
]
